### 토큰 생성 (유효기간 : 1일)
POST http://localhost:8080/api/user/login3
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "1111"
}

### 78. 관심사용자 등록
PUT http://localhost:8080/api/user/2/interest
Authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDIzNzY3NTAsInVzZXJfaWQiOjEsInN1YiI6InVzZXIxIiwiaXNzIjoidXNlcjFAZ21haWwuY29tIn0.71wz5e5Pe9sxjTG6YvZCffxr0bwpJowxDz-vNgDR1ly3PG0H5a9o0H8iV5h6pCx1nb_QRWyPw8k8-jdtyMqL3A

### 79. 관심사용자 해제
DELETE http://localhost:8080/api/interest/1
Authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDIzNzY3OTIsInVzZXJfaWQiOjIsInN1YiI6InVzZXIyIiwiaXNzIjoidXNlcjJAZ21haWwuY29tIn0.D4Qm2F-X33ObuCEJ1A5iJc6lFDhpH1nuMSdACC49u43aopIw_ibDbTbtbU1Wjr0ZED9XX5-rxtARjV2F8pWU0Q