### 31-1. 사용자 등록시 입력값이 유효하지 않은 경우 예외를 발생시키는 기능을 작성하시오.
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "email": "email@naver.com",
  "userName": "user",
  "password": "1111",
  "phone": "010-1234-5678"
}

### 31-2. 에러가 발생하는 경우
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "email": "",
  "userName": "",
  "password": "",
  "phone": ""
}

### 32. 사용자 정보를 입력받아서 저장하는 api를 작성하시오.
POST http://localhost:8080/api/user2
Content-Type: application/json

{
  "email": "email@naver.com",
  "userName": "user",
  "password": "1111",
  "phone": "010-1234-5678"
}

### 33. 사용자 정보를 수정하는 api를 작성하시오.
PUT http://localhost:8080/api/user/4
Content-Type: application/json

{
  "phone": "010-9876-5432"
}

### 34. 사용자 정보를 조회하는 api를 작성하시오.
GET http://localhost:8080/api/user/3

### 35. 사용자 정보를 조회하는 api를 작성하시오.
GET http://localhost:8080/api/user/4/notice