### 74. 게시글 신고 목록 조회
GET http://localhost:8080/api/admin/board/badreport

### 98. 문의 게시판에 답변을 달경우 메일을 전송
POST http://localhost:8080/api/admin/board/5/reply
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDU3MzY0MjIsInVzZXJfaWQiOjUsInN1YiI6ImhvbmVlODU4MyIsImlzcyI6ImhvbmVlODU4M0BuYXZlci5jb20ifQ.VD2xc11brKKXirDeyUHE9GX_1h1zhdAH_UZMBXftJsLyMD9EAxL8eH4lhGcLQ3BjP_OS1b4ZobZ8yBpb2KH3kA

{
  "replyContents": "답변 작성합니다."
}
