### 토큰 생성 (유효기간 : 1분)
POST http://localhost:8080/api/user/login3
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "1111"
}

### 75. 게시글의 스크랩 추가
PUT http://localhost:8080/api/board/1/scrap
Authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDIzNzIzNjUsInVzZXJfaWQiOjEsInN1YiI6InVzZXIxIiwiaXNzIjoidXNlcjFAZ21haWwuY29tIn0.1Wm_wy_dtuKaDyeT7ZdYZobLQcwTeY0NQGP_y55EjvYinv-DxInEmJRcHVEbD71JE9FIbukqQY2rVxWbEuIz_A

### 76. 게시글의 스크랩 삭제
DELETE http://localhost:8080/api/scrap/1
Authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDIzNzIzODMsInVzZXJfaWQiOjIsInN1YiI6InVzZXIyIiwiaXNzIjoidXNlcjJAZ21haWwuY29tIn0.V8vHNbbf7zTcMO98tj4RwMQn0corQMPiqxn6o63oQjGvJ8RaYQZAyt21izAwNuFVB_vooNp7zlPOSIUqrwHfSg