### 61. 게시판 타입을 추가하는 api를 작성하시오.
POST http://localhost:8080/api/board/type
Content-Type: application/json

{
  "name": "게시판1"
}

### 62. 게시판 타입을 수정하는 api를 작성하시오.
PUT http://localhost:8080/api/board/type/1
Content-Type: application/json

{
  "name": "수정된게시판1"
}

### 63. 게시판 타입을 삭제하는 api를 작성하시오.
DELETE http://localhost:8080/api/board/type/1

### 64. 모든 게시판 타입 목록을 리턴하는 api를 작성하시오.
GET http://localhost:8080/api/board/type/list

### 65. 게시판 타입의 사용여부를 설정하는 api를 작성하시오.
PATCH http://localhost:8080/api/board/type/1/using
Content-Type: application/json

{
  "usingYn": false
}

### 66. 게시판별 작성된 게시글의 개수를 리턴하는 api를 작성하시오.
GET http://localhost:8080/api/board/type/count

### 67. 게시글을 최상단에 배치하는 api를 작성하시오.
PATCH http://localhost:8080/api/board/1/top

### 68. 게시글을 최상단배치에서 해제하는 api를 작성하시오.
PATCH http://localhost:8080/api/board/1/top/clear

### 69. 게시글의 게시기간을 시작일과 종요일로 설정하는 api를 작성하시오.
PATCH http://localhost:8080/api/board/1/publish
Content-Type: application/json

{
  "startDate": "2023-12-09",
  "endDate": "2023-12-10"
}

### 70. 게시글의 조회수 증가
PUT http://localhost:8080/api/board/1/hits
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDIyMDkzMjksInVzZXJfaWQiOjEsInN1YiI6InVzZXIxIiwiaXNzIjoidXNlcjFAZ21haWwuY29tIn0.ckGFavB9XoZo_r80VKag2S_qo1m3o5XXqmOkh8NAUj9KkEIOrfTdtZ-LpBwe-WMeAydB7-yTbulb9V2meIAwvQ

### 70-1 JWT 토큰 생성
POST http://localhost:8080/api/user/login3
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "1111"
}

### 71. 게시글에 대한 좋아요하기 기능을 수행하는 api를 작성하시오.
PUT http://localhost:8080/api/board/1/like
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDIyODE2MzUsInVzZXJfaWQiOjEsInN1YiI6InVzZXIxIiwiaXNzIjoidXNlcjFAZ21haWwuY29tIn0.e8BKfT5FGKhJYhPZ9ePGqdlPW5NgA3we_3JZjpwpjwX29bLaCUgl0K2MTTM3yI43jPl1zwm5qW1cMQhZNWAsmw

### 71-1 JWT 토큰 생성
POST http://localhost:8080/api/user/login3
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "1111"
}

### 72. 게시글의 좋아요 취소
PUT http://localhost:8080/api/board/1/unlike
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDIyODE2MzUsInVzZXJfaWQiOjEsInN1YiI6InVzZXIxIiwiaXNzIjoidXNlcjFAZ21haWwuY29tIn0.e8BKfT5FGKhJYhPZ9ePGqdlPW5NgA3we_3JZjpwpjwX29bLaCUgl0K2MTTM3yI43jPl1zwm5qW1cMQhZNWAsmw

### 73. 게시글 신고
PUT http://localhost:8080/api/board/1/badreport
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDIyOTgzODcsInVzZXJfaWQiOjEsInN1YiI6InVzZXIxIiwiaXNzIjoidXNlcjFAZ21haWwuY29tIn0.4QKcX-4MMJtCNFG_hmAY7KROtAMc7y1xwCku4O8PzZG_NUrVQakj_eQVGFpGB9SYfNF1VQAX-p5TpcsREj7w3g

{
  "comments": "신고합니다."
}

### 85. 게시판 상세조회내역 로깅
GET http://localhost:8080/api/board/1

### 92. 게시판 목록 리턴
GET http://localhost:8080/api/board

### 93. 게시글 등록
POST http://localhost:8080/api/board
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDU0Nzg3MjIsInVzZXJfaWQiOjEsInN1YiI6InVzZXIxIiwiaXNzIjoidXNlcjFAZ21haWwuY29tIn0.ItDgFiTz8N1yw9XMjI_72CqZgSOtbcGC2NsaGlC59YYzsHX8TP4oxp6AhF2mmmzdqQzeRy7ttxZROCj6mEB2lA

{
  "boardType": 1,
  "title": "게시글 제목입니다.",
  "contents": "게시글 내용입니다."
}

### 로그인
POST http://localhost:8080/api/user/login3
Content-Type: application/json

{
"email": "honee8583@naver.com",
"password": "1111"
}

### 97
POST http://localhost:8080/api/board2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDU3MDI4NDcsInVzZXJfaWQiOjUsInN1YiI6ImhvbmVlODU4MyIsImlzcyI6ImhvbmVlODU4M0BuYXZlci5jb20ifQ.hf1xh74xxEVI78zeQrkanAdmUgZWHDt1hTZCtBG5O6Vxv7Tubuxg9mPm4OCs8jvcuuRs_da-iqkdEmCqOptwDA

{
  "boardType": 1,
  "title": "게시글 제목입니다.",
  "contents": "게시글 내용입니다."
}
